"use strict";

const ERROR_CODES = Object.freeze({
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  ROUTE_VALIDATION_FAILED: "ROUTE_VALIDATION_FAILED",
  TRIP_NOT_FOUND: "TRIP_NOT_FOUND",
  TRIP_VALIDATION_FAILED: "TRIP_VALIDATION_FAILED",
  TRIP_REFERENCE_INVALID: "TRIP_REFERENCE_INVALID",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  FORBIDDEN_ROLE: "FORBIDDEN_ROLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  AUTH_VALIDATION_FAILED: "AUTH_VALIDATION_FAILED",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_REGISTER_FAILED: "AUTH_REGISTER_FAILED",
  INCIDENT_VALIDATION_FAILED: "INCIDENT_VALIDATION_FAILED",
  INCIDENT_CREATE_FAILED: "INCIDENT_CREATE_FAILED",
  INCIDENT_NOT_FOUND: "INCIDENT_NOT_FOUND",
});

module.exports = { ERROR_CODES };
