"use strict";

const ERROR_CODES = Object.freeze({
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  ROUTE_VALIDATION_FAILED: "ROUTE_VALIDATION_FAILED",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  FORBIDDEN_ROLE: "FORBIDDEN_ROLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
});

module.exports = { ERROR_CODES };
