CREATE TYPE "user_role" AS ENUM (
  'Passenger',
  'Driver',
  'Admin'
);

CREATE TYPE "trip_status" AS ENUM (
  'Scheduled',
  'Pending',
  'In_Progress',
  'Stopped',
  'Delayed',
  'Completed',
  'Cancelled'
);

CREATE TYPE "ticket_status" AS ENUM (
  'Generated',
  'Scanned',
  'Cancelled'
);

CREATE TYPE "payment_type" AS ENUM (
  'Simulated_Card',
  'Senior_Exemption'
);

CREATE TYPE "report_type" AS ENUM (
  'Accident',
  'Delay',
  'Traffic_Congestion',
  'Overcrowding',
  'Road_Problem',
  'Mechanical_Failure',
  'Other'
);

CREATE TYPE "notification_status" AS ENUM (
  'Pending',
  'Sent',
  'Read',
  'Failed'
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "name" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "role" user_role NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "passengers" (
  "user_id" uuid PRIMARY KEY,
  "phone" varchar(30),
  "notification_preferences" jsonb,
  "is_senior" boolean DEFAULT false,
  "expo_push_token" varchar(255)
);

CREATE TABLE "drivers" (
  "user_id" uuid PRIMARY KEY,
  "license_number" varchar(80) NOT NULL
);

CREATE TABLE "administrators" (
  "user_id" uuid PRIMARY KEY,
  "employee_code" varchar(80) UNIQUE NOT NULL
);

CREATE TABLE "buses" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "plate_number" varchar(30) UNIQUE NOT NULL,
  "capacity" integer NOT NULL,
  "status" varchar(50) NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "routes" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "name" varchar(100) NOT NULL,
  "origin" varchar(150) NOT NULL,
  "destination" varchar(150) NOT NULL,
  "geometry_geojson" jsonb NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "stops" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "route_id" uuid NOT NULL,
  "name" varchar(120) NOT NULL,
  "latitude" numeric(10,7) NOT NULL,
  "longitude" numeric(10,7) NOT NULL,
  "stop_order" integer NOT NULL
);

CREATE TABLE "trips" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "route_id" uuid NOT NULL,
  "bus_id" uuid NOT NULL,
  "driver_id" uuid NOT NULL,
  "departure_time" timestamptz NOT NULL,
  "arrival_time" timestamptz,
  "status" trip_status NOT NULL DEFAULT 'Scheduled',
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "locations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trip_id" uuid NOT NULL,
  "user_id" uuid,
  "latitude" numeric(10,7) NOT NULL,
  "longitude" numeric(10,7) NOT NULL,
  "speed" numeric(8,2),
  "heading" numeric(8,2),
  "timestamp" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "reports" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "trip_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "type" report_type NOT NULL,
  "description" text,
  "latitude" numeric(10,7) NOT NULL,
  "longitude" numeric(10,7) NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "user_id" uuid NOT NULL,
  "trip_id" uuid,
  "message" text NOT NULL,
  "status" notification_status NOT NULL DEFAULT 'Pending',
  "timestamp" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "tickets" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "passenger_id" uuid NOT NULL,
  "trip_id" uuid NOT NULL,
  "status" ticket_status NOT NULL DEFAULT 'Generated',
  "payment_type" payment_type NOT NULL,
  "generated_at" timestamptz NOT NULL DEFAULT (now()),
  "scanned_at" timestamptz
);

CREATE TABLE "report_validations" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "report_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "vote_type" varchar(20) NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "passengers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "drivers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "administrators" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "stops" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "trips" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "trips" ADD FOREIGN KEY ("bus_id") REFERENCES "buses" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "trips" ADD FOREIGN KEY ("driver_id") REFERENCES "drivers" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "locations" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "locations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reports" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notifications" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tickets" ADD FOREIGN KEY ("passenger_id") REFERENCES "passengers" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tickets" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "report_validations" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "report_validations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stops" ADD CONSTRAINT "uq_stops_route_order" UNIQUE ("route_id", "stop_order");
ALTER TABLE "tickets" ADD CONSTRAINT "uq_tickets_passenger_trip" UNIQUE ("passenger_id", "trip_id");
ALTER TABLE "report_validations" ADD CONSTRAINT "uq_report_validations_report_user" UNIQUE ("report_id", "user_id");

CREATE INDEX "idx_trips_route_id" ON "trips" ("route_id");
CREATE INDEX "idx_trips_bus_id" ON "trips" ("bus_id");
CREATE INDEX "idx_trips_driver_id" ON "trips" ("driver_id");
CREATE INDEX "idx_locations_trip_timestamp" ON "locations" ("trip_id", "timestamp");
CREATE INDEX "idx_locations_user_id" ON "locations" ("user_id");
CREATE INDEX "idx_reports_trip_id" ON "reports" ("trip_id");
CREATE INDEX "idx_reports_user_id" ON "reports" ("user_id");
CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id");
CREATE INDEX "idx_notifications_trip_id" ON "notifications" ("trip_id");
CREATE INDEX "idx_tickets_trip_id" ON "tickets" ("trip_id");
CREATE INDEX "idx_report_validations_user_id" ON "report_validations" ("user_id");;
