-- Migration: create public.trip_location for the live fleet dashboard (US-09)
-- The admin web console subscribes with the anon key to postgres_changes INSERT
-- on this table (per trip) to move bus markers in real time. Every driver
-- telemetry point is mirrored here by the backend (best-effort dual-write).

create table if not exists public.trip_location (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips (id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  speed double precision,
  heading double precision,
  timestamp timestamptz not null default now()
);

create index if not exists trip_location_trip_id_timestamp_idx
  on public.trip_location (trip_id, timestamp desc);

alter table public.trip_location enable row level security;

create policy trip_location_anon_select
  on public.trip_location
  for select
  using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'trip_location'
  ) then
    alter publication supabase_realtime add table public.trip_location;
  end if;
end $$;
